### ISSUE TITLE
duplicity on CentOS 7 fails to install

### ISSUE THREAD

**Issue by ttasovac** [onnozweers/scripts#2]
Hi @onnozweers! 

I was very happy to discover your script —  I also need the latest version on duplicity on CentOS (release 7.9.2009). On my server, the script runs till the end but ultimately fails:

```
Checking `duplicity --version`:
./install-duplicity.sh: line 48: duplicity: command not found
./install-duplicity.sh: line 49: SupportCancel: command not found
./install-duplicity.sh: line 50: Full-text: command not found
```

I think it may have to do with this:

```
No package python3-paramiko available.
No package python3-crypto available.
No package python3-boto available.
```

Full log is here https://gist.github.com/ttasovac/54ad4ae2be4bb9a81a5cb95ef682a9ed 

Do you have a recommendation how to proceed? Many thanks in advance. 

All best,
Toma

**Comment by onnozweers** [comment]
Hi Toma,

Could you try the package names without the 3? So,

```
[root@host ~]# yum install python3-paramiko
...
No package python3-paramiko available.

[root@host ~]# yum install python-paramiko
...
---> Package python-paramiko.noarch 0:2.1.1-9.el7 will be installed
```

Let me know whether that works.

Cheers,
Onno

**Comment by ttasovac** [comment]
Yup, that definitely did it! Thank a lot for making the script available and helping me out with this. It's much appreciated. 

All best,
Toma

**Comment by onnozweers** [comment]
Hi Toma,

Thanks for checking. I'll fix the script.

Cheers,
Onno

**Comment by ttasovac** [comment]
actually, i spoke a little too soon —  i had no errors running the script all the way but when i ran my duplicity script I still got the error about paramiko. so what i did then is to install boto, crypto and parimiko manually with `pip3 install `. Not sure why, but figuring it out is way above my pay grade :)

**Comment by onnozweers** [comment]
Ah, thanks for the additional info. I guess I'll have to check on a fresh system what exactly duplicity needs nowadays.
